ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: debug-statements
      - id: file-contents-sorter
        files: |
          (?x)^(
              .github/workflows/script/formatScan/nlp_dict.txt
          )$
        args: [--unique]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: [-w]
        exclude: |
          (?x)^(
              docker/third_party_programs_docker.txt|
              intel_extension_for_transformers/llm/evaluation/hf_eval/datasets/cnn_validation.json|
              examples/huggingface/pytorch/text-generation/inference/prompt.json|
              intel_extension_for_transformers/llm/runtime/deprecated/oneDNN-THIRD-PARTY-PROGRAMS|
              docker/intel-tensorflow-third-party-programs.txt|
              intel_extension_for_transformers\llm\evaluation\hf_eval\datasets\cnn_validation.json|
              .github\workflows\sample_data\alpaca_data_sample_45.json|
              intel_extension_for_transformers/neural_chat/assets/docs/4th\ Generation\ Intel®\ Xeon®\ Scalable\ Processors\ Product\ Specifications.html
          )$
