matrix:
- name: Markdown
  aspell:
    lang: en
    d: en_US
    mode: markdown
  dictionary:
    wordlists:
      - ${VAL_REPO}/nlp_dict.txt
    output: ${VAL_REPO}/nlp_dict.dic
  sources:
  - ${SCAN_REPO}/docs/*
  - ${SCAN_REPO}/*.md