#!/usr/bin/env python
import requests
import unittest
from neural_chat.tests.restful.config import HOST, API_ASR, API_TTS
from neural_chat.cli.log import logger
from neural_chat.pipeline.plugins.audio.asr import AudioSpeechRecognition


class UnitTest(unittest.TestCase):

    def __init__(self, *args):
        super(UnitTest, self).__init__(*args)
        self.host = HOST

    def test_asr(self):
        logger.info(f'Testing POST request: {self.host+API_ASR}')
        request = ""
        response = requests.post(self.host+API_ASR, json=request)
        logger.info('Response status code: {}'.format(response.status_code))
        logger.info('Response text: {}'.format(response.text))
        self.assertEqual(response.status_code, 200, msg="Abnormal response status code.")

    def test_tts(self):
        logger.info(f'Testing POST request: {self.host+API_TTS}')
        request = "Hello, nice to meet you!"
        response = requests.post(self.host+API_TTS, data=request)
        logger.info('Response status code: {}'.format(response.status_code))
        logger.info('Response voice: {}'.format(response.voice))
        self.assertEqual(response.status_code, 200, msg="Abnormal response status code.")


if __name__ == "__main__":
    unittest.main()