version: "3"
services:
  devel:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ""
        IMAGE_NAME: ubuntu
        IMAGE_TAG: 22.04
        PYTHON: python3.10
      context: ../
      dockerfile: ./docker/Dockerfile_code_gen
      target: devel
    command: python tests/test_config.py
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    image: intel/ai-tools:itrex-devel-latest
    privileged: true
  prod:
    extends:
      service: devel
    build:
      target: prod
    image: intel/ai-tools:itrex-prod-latest
