import subprocess
import sys
import q_bits
import os.path as path

try:
    from ._version import __version__  # load _version file generated by setuptools_scm 
except ModuleNotFoundError:
    __version__ = "0.0.0"


def q_bits_bin():
    ''' Entry point for C++ interface '''
    q_bits_bin = path.join(
        q_bits.__path__[0], 'q_bits_bin')
    raise SystemExit(subprocess.call(
        [q_bits_bin] + sys.argv[1:], close_fds=False))
