python ./run_glue_no_trainer.py \
        --model_name_or_path "bert_base_uncased" \
        --pruning_config "./bert_base_mrpc_4x1.yaml" \
        --task_name "mrpc" \
        --max_length "128" \
        --per_device_train_batch_size "16" \
        --learning_rate 5e-5 \
        --distill_loss_weight 2.0 \
        --num_train_epochs 15 \
        --weight_decay 5e-5   \
        --cooldown_epochs 5 \
        --sparsity_warm_epochs 0\
        --lr_scheduler_type "constant"\
        --do_prune