name: Chatbot inference on llama-2-7b-chat-hf

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-inf-lla-7b
  cancel-in-progress: true

jobs:
  inference:
    name: inference test
    runs-on: lms-lab
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load environment variables
        run: cat ~/itrex-actions-runner/.env >> $GITHUB_ENV
      
      - name: Prepare Cache
        run: cp ${{ env.CACHE }}/torch/* ./

      - name: Build Docker Image
        run: 
          if [ $(docker images | grep chatbotinfer | wc -l) == 0 ]; then
            docker build ./ --target cpu --build-arg REPO=${{ github.server_url }}/${{ github.repository }}.git --build-arg ITREX_VER=${{ github.head_ref }} --build-arg http_proxy="${{ env.HTTP_PROXY_IMAGE_BUILD }}" --build-arg https_proxy="${{ env.HTTPS_PROXY_IMAGE_BUILD }}" -f intel_extension_for_transformers/neural_chat/docker/Dockerfile -t chatbotinfer:latest && yes | docker container prune && yes | docker image prune;
          fi

      - name: Start Docker Container
        run: |
          cid=$(docker ps -q --filter "name=chatbotinfer")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi
          docker run -tid -v /mnt/DP_disk1/huggingface/cache/:/root/.cache/huggingface/hub -v .:/root/chatbot -e http_proxy="${{ env.HTTP_PROXY_CONTAINER_RUN }}" -e https_proxy="${{ env.HTTPS_PROXY_CONTAINER_RUN }}" --name="chatbotinfer" --hostname="chatbotinfer-container" chatbotinfer:latest

      - name: Run Inference Test
        run: |
          docker exec "chatbotinfer" bash -c "cd /root/chatbot && source activate && conda activate neuralchat;\
                 pip uninstall intel-extension-for-transformers -y; \
                 pip install -r requirements.txt; \
                 python setup.py install; \
                 pip install -r intel_extension_for_transformers/neural_chat/requirements.txt; \
                 python workflows/chatbot/inference/generate.py --base_model_path \"meta-llama/Llama-2-7b-chat-hf\" --hf_access_token \"${{ env.HF_ACCESS_TOKEN }}\" --instructions \"Transform the following sentence into one that shows contrast. The tree is rotten.\" "

      - name: Stop Container
        if: success() || failure()
        run: |
          cid=$(docker ps -q --filter "name=chatbotinfer")
          if [[ ! -z "$cid" ]]; then docker stop $cid && docker rm $cid; fi

      - name: Test Summary
        run: echo "Inference completed successfully"
