name: Chat Bot Finetuning Test

on:
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-finetune-mpt-7b-chat:
    uses: ./.github/workflows/chatbot-finetune-mpt-7b-chat.yml

